baseURL = "https://seedofyoga.com/"
title = "Seed of Yoga"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[pagination]
  pagerSize = 9

[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    languageName = "EN"
    weight = 1
    [languages.en.params]
      description = "Yoga classes in Narbonne"
      tagline = "Yoga classes in Narbonne"
    [[languages.en.menu.main]]
      name = "Schedule"
      url = "/#schedule"
      weight = 1
    [[languages.en.menu.main]]
      name = "Pricing"
      url = "/#pricing"
      weight = 2
    [[languages.en.menu.main]]
      name = "About"
      url = "/#about"
      weight = 3
    [[languages.en.menu.main]]
      name = "Location"
      url = "/#location"
      weight = 4
    [[languages.en.menu.main]]
      name = "Blog"
      url = "/blog/"
      weight = 5
    [[languages.en.menu.main]]
      name = "Contact"
      url = "/#contact"
      weight = 6

  [languages.fr]
    languageName = "FR"
    weight = 2
    [languages.fr.params]
      description = "Cours de yoga sur Narbonne"
      tagline = "Cours de yoga sur Narbonne"
    [[languages.fr.menu.main]]
      name = "Horaires"
      url = "/fr/#schedule"
      weight = 1
    [[languages.fr.menu.main]]
      name = "Tarifs"
      url = "/fr/#pricing"
      weight = 2
    [[languages.fr.menu.main]]
      name = "À propos"
      url = "/fr/#about"
      weight = 3
    [[languages.fr.menu.main]]
      name = "Adresse"
      url = "/fr/#location"
      weight = 4
    [[languages.fr.menu.main]]
      name = "Blog"
      url = "/fr/blog/"
      weight = 5
    [[languages.fr.menu.main]]
      name = "Contact"
      url = "/fr/#contact"
      weight = 6
