baseURL = "https://seedofyoga.com/"
title = "Seed of Yoga"
locale = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[pagination]
  pagerSize = 9

[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    label = "EN"
    weight = 1
    [languages.en.params]
      description = "Yoga classes - Coming soon"
      tagline = "Yoga classes - Coming soon"
    [[languages.en.menu.main]]
      name = "Classes"
      url = "/#classes"
      weight = 1
    [[languages.en.menu.main]]
      name = "Pricing"
      url = "/#pricing"
      weight = 2
    [[languages.en.menu.main]]
      name = "About"
      url = "/#about"
      weight = 3
    # [[languages.en.menu.main]]
    #   name = "Location"
    #   url = "/#location"
    #   weight = 4
    [[languages.en.menu.main]]
      name = "Blog"
      url = "/blog/"
      weight = 5
    [[languages.en.menu.main]]
      name = "Contact"
      url = "/#contact"
      weight = 6

  [languages.fr]
    label = "FR"
    weight = 2
    [languages.fr.params]
      description = "Cours de yoga - Coming soon"
      tagline = "Cours de yoga - Coming soon"
    [[languages.fr.menu.main]]
      name = "Cours"
      url = "/fr/#classes"
      weight = 1
    [[languages.fr.menu.main]]
      name = "Tarifs"
      url = "/fr/#pricing"
      weight = 2
    [[languages.fr.menu.main]]
      name = "À propos"
      url = "/fr/#about"
      weight = 3
    # [[languages.fr.menu.main]]
    #   name = "Adresse"
    #   url = "/fr/#location"
    #   weight = 4
    [[languages.fr.menu.main]]
      name = "Blog"
      url = "/fr/blog/"
      weight = 5
    [[languages.fr.menu.main]]
      name = "Contact"
      url = "/fr/#contact"
      weight = 6
